# Generated by Django 3.0.9 on 2020-08-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytag',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='api.CategoryTag', verbose_name='Относится'),
        ),
    ]
