# Generated by Django 3.0.9 on 2020-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201014_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IID'),
        ),
    ]
