# Generated by Django 3.0.9 on 2020-08-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200803_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='api.CategoryTag', verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='item',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Видео локальный файл'),
        ),
        migrations.AlterField(
            model_name='item',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео ссылка'),
        ),
        migrations.AlterField(
            model_name='itemrecomendationimage',
            name='order_num',
            field=models.IntegerField(default=1, verbose_name='Порядок вывода'),
        ),
    ]
