# Generated by Django 3.0.9 on 2020-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201014_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ItemStatus',
        ),
    ]
