# Generated by Django 3.0.9 on 2020-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200803_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecomendationimage',
            name='image_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Текст на картинку'),
        ),
    ]
