# Generated by Django 3.0.9 on 2020-08-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_itemrecomendationimage_image_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemRecomendationSubBlockBImage',
            new_name='ItemRecomendationBlockBImage',
        ),
        migrations.AlterField(
            model_name='itemrecomendationblockbimage',
            name='block_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendation_sub_block_b_images', to='api.ItemRecomendationBlockB', verbose_name='Относится к'),
        ),
    ]
