# Generated by Django 3.0.9 on 2020-10-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201014_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('iid', models.CharField(blank=True, max_length=255, null=True, verbose_name='IID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Еденица оборудования',
                'verbose_name_plural': 'Еденицы оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquimentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('check_date', models.DateField(blank=True, null=True)),
                ('calibrate_date', models.DateField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Equiment', verbose_name='Партия товара')),
            ],
        ),
    ]
