# Generated by Django 3.0.9 on 2020-10-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201019_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquimentTestDateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='SampleExpirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('subject', models.CharField(max_length=255, null=True, verbose_name='На что')),
                ('weight', models.CharField(max_length=255, null=True, verbose_name='Вес')),
                ('iso', models.CharField(max_length=255, null=True, verbose_name='Стандарт')),
            ],
        ),
        migrations.CreateModel(
            name='SampleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.RenameField(
            model_name='equimenttest',
            old_name='calibrate_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='equimenttest',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='equimenttest',
            name='test_date',
        ),
        migrations.AddField(
            model_name='equimenttest',
            name='event',
            field=models.CharField(max_length=255, null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='equimenttest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Equiment'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(blank=True, max_length=255, null=True, verbose_name='IID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('expirement', models.ManyToManyField(blank=True, null=True, to='api.SampleExpirement')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SampleState')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SampleType')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
        migrations.AddField(
            model_name='equimenttest',
            name='date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.EquimentTestDateType'),
        ),
    ]
