# Generated by Django 3.0.9 on 2020-08-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200804_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_lower',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
