# Generated by Django 3.0.9 on 2020-10-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_manufacturer_sampleexpirementfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_close_sample',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='date_get_sample',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='equimenttest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='api.Equiment'),
        ),
    ]
