# Generated by Django 3.0.9 on 2020-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201025_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='arrived',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поступило'),
        ),
        migrations.AddField(
            model_name='sample',
            name='broken',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скисло'),
        ),
        migrations.AddField(
            model_name='sample',
            name='done',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сделано'),
        ),
        migrations.AddField(
            model_name='sample',
            name='go_bad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Непригодны'),
        ),
        migrations.AddField(
            model_name='sample',
            name='too_small',
            field=models.IntegerField(blank=True, null=True, verbose_name='Малый объем'),
        ),
    ]
