# Generated by Django 3.0.9 on 2020-11-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201103_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='min_number',
            field=models.IntegerField(default=0),
        ),
    ]
