# Generated by Django 3.0.9 on 2020-11-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subcategory_min_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiment',
            name='start_work',
            field=models.DateField(blank=True, null=True),
        ),
    ]
