# Generated by Django 3.0.9 on 2020-11-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_equiment_start_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiment',
            name='manufactor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
    ]
