# Generated by Django 3.0.9 on 2020-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_female',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_male',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
